site_name: Microbiologia
copyright: 2023 Luiza H. Moretti
repo_name: RESUMOS
repo_url: https://luhm.github.io/microbiologia/

theme:
  name: material
#  icon:
#    logo: material/library-house
  features:
    - content.code.annotate
    - content.code.copy
 
  favicon: assets/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
   - attr_list
   - pymdownx.caret
   - pymdownx.mark
   - pymdownx.tilde
   - footnotes
   - pymdownx.smartsymbols

nav:
  - Microbiologia:
    - Informações Gerais: microbiologia/m4d2_microbiologia.md
    - Conteúdo:
      - Geral: microbiologia/micro_conteudo.md
      - Microbiologia - Anvisa:
        - Módulo 4: microbiologia/micro_anvisa_mod4.md
        - Módulo 6: microbiologia/micro_anvisa_mod6.md
      - Microbiologia de Brock:
        - Capítulo 2: microbiologia/m4d2_microbiologia_de_brock_2.md
        - Capítulo 3: microbiologia/m4d2_microbiologia_de_brock_3.md
        - Capítulo 27: microbiologia/m4d2_microbiologia_de_brock_27.md
        - Miniquestionários: microbiologia/micro_de_brock_miniquest_cap2.md
    - Avaliações: microbiologia/micro_avaliacoes.md
    
